# Generated by Django 4.2.4 on 2023-08-21 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultuser',
            name='second_name',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
