# Generated by Django 4.2.4 on 2023-08-22 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_defaultuser_second_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserApprovalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('browser', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.CharField(blank=True, max_length=255)),
                ('approval_time', models.DateTimeField()),
                ('approval_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.approvalrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
