# Generated by Django 4.2.4 on 2023-08-23 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_userapprovaldata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalrequest',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='main.document'),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
