# Generated by Django 4.2.4 on 2023-08-17 03:42

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_document_file_approvalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultuser',
            name='sign_image',
            field=models.ImageField(blank=True, upload_to=main.models.image_upload_path),
        ),
    ]
