# Generated by Django 4.2.4 on 2023-08-23 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_approvalrequest_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultuser',
            name='job_position',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
