# Generated by Django 4.2.4 on 2023-08-17 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_defaultuser_sign_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvalrequest',
            name='is_approved',
        ),
    ]
