# Generated by Django 4.2.4 on 2023-08-28 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_defaultuser_job_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalrequest',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='main.document', verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Статус подтверждения'),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='receivers',
            field=models.ManyToManyField(related_name='receivers', through='main.RequestReceivers', to=settings.AUTH_USER_MODEL, verbose_name='Получатели'),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата запроса'),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель'),
        ),
        migrations.AlterField(
            model_name='defaultuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='внутренняя почта'),
        ),
        migrations.AlterField(
            model_name='defaultuser',
            name='first_name',
            field=models.CharField(max_length=128, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='defaultuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='defaultuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Доступ к админ панели'),
        ),
        migrations.AlterField(
            model_name='defaultuser',
            name='job_position',
            field=models.CharField(blank=True, max_length=255, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='defaultuser',
            name='last_name',
            field=models.CharField(max_length=128, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='defaultuser',
            name='second_name',
            field=models.CharField(max_length=128, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='defaultuser',
            name='sign_image',
            field=models.ImageField(blank=True, upload_to=main.models.image_upload_path, verbose_name='Изображение подписи'),
        ),
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.CharField(max_length=128, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(unique=True, upload_to=main.models.file_upload_path, validators=[main.validators.validate_pdf], verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='document',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Статус подтверждения'),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки'),
        ),
        migrations.AlterField(
            model_name='document',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
    ]
