# Generated by Django 4.2.4 on 2023-08-17 07:04

from django.db import migrations, models
import main.models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_approvalrequest_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(unique=True, upload_to=main.models.file_upload_path, validators=[main.validators.validate_pdf]),
        ),
    ]
