# Generated by Django 4.2.4 on 2023-08-17 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrequest',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
