# Generated by Django 4.2.4 on 2023-08-28 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_approvalrequest_document_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approvalrequest',
            options={'verbose_name_plural': 'Заявки на согласование'},
        ),
        migrations.AlterModelOptions(
            name='defaultuser',
            options={'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name_plural': 'Документы'},
        ),
    ]
