# Generated by Django 4.2.4 on 2023-09-01 08:03

from django.db import migrations, models
import main.models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_approvalrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestreceivers',
            options={'verbose_name_plural': 'Получатели'},
        ),
        migrations.AlterField(
            model_name='defaultuser',
            name='sign_image',
            field=models.ImageField(blank=True, upload_to=main.models.image_upload_path, validators=[main.validators.validate_png], verbose_name='Изображение подписи'),
        ),
    ]
