# Generated by Django 4.2.4 on 2023-09-01 10:31

from django.db import migrations, models
import main.models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_requestreceivers_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultuser',
            name='job_position',
            field=models.CharField(max_length=255, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='defaultuser',
            name='sign_image',
            field=models.ImageField(upload_to=main.models.image_upload_path, validators=[main.validators.validate_png], verbose_name='Изображение подписи'),
        ),
    ]
