
# Generated by Django 4.2.4 on 2023-09-25 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_defaultuser_job_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestreceivers',
            name='comment',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='requestreceivers',
            name='is_disapproved',
            field=models.BooleanField(default=False),
        ),
    ]
